- name: Install Docker and Kubernetes
  hosts: web
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install kubeadm, kubelet, kubectl
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: yes
